# -*- coding: utf-8 -*-
"""mkt_bot.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1R2eNxg9fOpfs6QYct23rWXnmu9QyzmEq
"""

import requests, json, openai
import re
from urllib.parse import quote
import os

# === 설정 ===
company_intro = """
우리 회사는 선불·후불 교통카드의 발급 및 정산, NFC 충전, 시외버스 예매, 지자체 통합패스(교통카드 정기권) 등 대중교통 중심의 결제·발급 인프라를 운영합니다.
이러한 플랫폼 운영 경험과 기술 인프라를 바탕으로, 다양한 산업과 공공영역에 적용 가능한 새로운 결제, 정산, 유통, 인증 기반 사업 기회를 탐색하고자 합니다. 기존 시스템이 확장되거나 전환 적용될 수 있는 모든 분야에 대해 선제적 리서치를 수행하려합니다.


"""                                   # ← 원하는 만큼 자세히 넣기
perplexity_api_key = os.environ["PERPLEXITY_API_KEY"]
openai_api_key     = os.environ["OPENAI_API_KEY"]
teams_webhook_url  = os.environ["TEAMS_WEBHOOK_URL_TEST"]

pplx_headers = {
    "Authorization": f"Bearer {perplexity_api_key}",
    "Content-Type":  "application/json"
}

# === STEP 0: GPT가 키워드 추천 ===
keyword_prompt = (
    company_intro.strip() +
    "\n\n우리 회사는 대중교통 분야에서 다양한 서비스를 운영 중입니다.\n"
    "이를 바탕으로 **미래 전략 수립에 참고할 수 있는 최근 주요 트렌드나 이슈를 반영한 '한국어 키워드 총 8개'를 추천**해주세요.\n"
    "- 필수로 포함하는 키워드는 '자율주행', '모빌리티', '교통정산'입니다 \n   "
    "- 필수 키워드 이외 키워드는 **검색 가능한 일반 명사 2개** , 뉴스 검색이 잘 되는 수준의 **적절한 단어 조합 3개** 를 추천해주세요 (예: '모바일결제', '대중교통', '교통카드', '시외버스', '교통 요금' ,'NFC 충전','교통 정기권' 등).\n"
    "- 너무 좁거나 합성도가 높은 키워드는 피해주세요.\n"
    "- 키워드는 **쉼표로 구분된 한 줄 리스트**로만 작성해주세요.\n"
    "- 다음 키워드는 반드시 제외해주세요: '빅데이터', '합성데이터', '기후동행', '티머니', '마이비', '한페이시스', '부산하나로카드',  '캐시비'          \n"
)

client = openai.OpenAI(api_key=openai.api_key)
resp = client.chat.completions.create(
    model="gpt-4.1-mini",
    messages=[{"role": "user", "content": keyword_prompt}]
)
kw_text = resp.choices[0].message.content
keywords = [k.strip() for k in re.split("[,·\n]", kw_text) if k.strip()]
print("🔑 추천 키워드 →", keywords)
keywords_str = ", ".join(keywords)

# === STEP 1: 키워드별 뉴스 수집 ===
news_chunks = []
for kw in keywords:
    payload = {
        "model": "sonar-pro",
        "messages": [
            {"role": "user",
             "content": f""" '{kw}' 관련 최근 7일 뉴스나 정보를 표 형식으로 정리해줘
                        각 키워드별 '제목', '원문 링크', ' 키워드', '핵심 요약'이 반드시 포함되도록 해줘
                        ※ 주의: 최근 7일이내 뉴스 & 링크 이어야하며 최근 7일까지로 엄격히 제한합니다
                        원문링크를 반드시 포함하고 실주소가 https:// 로 시작하는 완전한 링크여야 합니다 '링크 없음', '링크 대체 필요', '기사 링크 참조' 등의 문구가 들어가면 오류입니다
                        """}
        ],
        "search": {
            "enable": True,
            "num_results": 5,
            "time_range": "7d",
            "language": "ko",
            "query": kw
        }
    }
    r = requests.post("https://api.perplexity.ai/chat/completions",
                      headers=pplx_headers, json=payload, timeout=600)
    raw_content = r.json()["choices"][0]["message"]["content"]
    print(f"\n\n📰 키워드: {kw}\n{raw_content}\n{'='*80}")
    news_chunks.append(raw_content)

# news_text 정의
news_text = "\n\n".join(news_chunks)

# === STEP 2: GPT 분석 프롬프트 구성 ===
gpt_prompt = f"""
각 기사에는 기사 제목, 원문 링크, 핵심 내용 요약이 포함되어 있습니다.
모든 뉴스들을 전부 읽고 다음 내용을 포함한 보고서를 작성해주세요:

헤더 :  AI 뉴스 주간 보고서

---

🔑 AI추천 검색 키워드 → {keywords_str}

---

1. **뉴스 요약**
   - 뉴스요약 공통 규칙 1 : 레이아웃은 표 형태 고정입니다. 모든 기사를 읽고 우리 회사와 관련 혹은 중요도가 높다고 생각하는 뉴스를 순서대로 나열해주세요 나열 갯수는 최대 20개로 제한합니다.
   - 뉴스요약 공통 규칙 2 : 각 행은 **번호 | 기사제목(원문링크) | 키워드 | 핵심 문장 요약 | ** 형식을 꼭 지킵니다
   - 뉴스요약 공통 규칙 3 : 원문링크는 마크다운 링크로 제공합니다
   ※ 주의: 원문링크는 반드시 실주소가 포함된 https:// 로 시작하는 완전한 링크여야 합니다. "링크 없음", "링크 대체 필요", "기사 링크 참조" 등의 문구가 들어가면 오류입니다.
   
---

2. **우리 회사 관점 리포트**
   - 우리 회사는 선불·후불 교통카드의 발급 및 정산, NFC 충전, 시외버스 예매, 지자체 통합패스(교통카드 정기권) 등 대중교통 중심의 결제·발급 인프라를 운영합니다.
이러한 플랫폼 운영 경험과 기술 인프라를 바탕으로, 다양한 산업과 공공영역에 적용 가능한 새로운 결제, 정산, 유통, 인증 기반 사업 기회를 탐색하고자 합니다. 기존 시스템이 확장되거나 전환 적용될 수 있는 모든 분야에 대해 선제적 리서치를 수행하려합니다
   - ① 이번주 주요 뉴스들의 동향 : 가져온 기사들의 주요 동향을 요약해주세요
   - ② 자사와 뉴스 관련성 : 본 기사들이 우리 회사와 어떤 관련이 있는지 설명해주세요.
   - ③ 이번 주 눈에 띄는 트렌드/정책·기술 변화 : 이번 주 이슈에서 눈에 띄는 트렌드 또는 정책/기술 변화가 있다면 강조해주세요.
   
---

3. **사업 기회 분석 (다음 세 가지 관점으로 구분하며 전략적으로 상세하게)**
- 분석 공통 규칙
  - 기사에서 직접 언급된 숫자·기관·지표가 있을 경우 **반드시 인라인 인용**(예: “2025년까지 12억 달러 규모”) 후 사용.
  - '이동의즐거움', '마이비', '부산하나로카드', '캐시비', '한페이시스'는 자사입니다 인수/투자/제휴 업체에 포함되었다면 제외 필요, 
  - '티머니'는 경쟁사로 내용에 포함될 경우 인수/투자는 불가능하지만 협업까지는 가능합니다

- **① 인수·투자 기회**
  - 기사 속 대상 회사·기술의 시너지 영역과 Risk 요인을 서술.
- **② 신사업 기회**
  - '대중교통', '결제·정산'과 같이 접점이 큰 **서비스 구조**를 그림 없이 텍스트로 간단히 개념화.
  - 새로운 사업 아이디어 또는 확장 가능한 영역 도출
- **③ 전략적 제휴 기회**
  - 파트너사 제안 시 협업 모델(공동 개발·데이터 교환·리셀링 등)과, Win-Win 논리를 서술
  
---  

하단 : 본 보고서는 최근 1주일간의 주요 뉴스와 현황을 바탕으로, 우리 회사의 사업 영역과 미래 전략 수립에 유의미한 인사이트를 생성형 AI가 도출한 결과입니다.

---
※ 보고서 공통 규칙
  ※ 각 분석 항목에 대해 가능한 한 구체적인 **타겟 업체명**이나 서비스명을 포함해 주세요.
  ※ 단 업체명이나 서비스명은 혼란을 방지하기 위해 기사에 존재하는 내용만 언급합니다.
  ※ 분석은 선제적 리서치 목적에 맞춰, 창의적이고 전략적인 인사이트 중심으로 작성해 주세요.
  ※ 위 리포트 순서, 형식(구조)은 엄격히 유지되야하며 가독성이 뛰어나야 합니다 
    - 각 대제목(1·2·3) 앞에는 반드시 **빈 줄 1줄 + 수평선(---)**을 삽입하고, 대제목 이후에도 빈 줄 1줄을 넣어 가독성을 확보하세요
    - 소제목(①-②-③) 간에도 **줄바꿈 후 빈 줄 1줄 추가**을 넣어 가독성을 높이십시오
    - 넘버링·볼드 처리를 유지하되, 문단간에 간격은 빈줄을 추가하여 가독성을 높이세요
    - 글자 크기는 일정하게 유지합니다.
  
--- 기사 목록 ---
{news_text}
"""

# === STEP 3: GPT에게 분석 요청 ===
client = openai.OpenAI(api_key=openai.api_key)
response = client.chat.completions.create(
    model="ft:gpt-4.1-2025-04-14:::BiquLkMh",  # 모델명 정확하게
    messages=[{"role": "user", "content": gpt_prompt}]
)
report_text = response.choices[0].message.content

# === STEP 4: Teams 전송 ===
def send_to_teams(message):
    res = requests.post(teams_webhook_url, json={"text": message})
    print("✅ 전송 완료" if res.status_code == 200 else f"❌ 전송 실패: {res.text}")

send_to_teams(report_text)

