name: test-cron

on:
  schedule:
    - cron: '*/5 * * * *'
  workflow_dispatch:

jobs:
  ping:
    runs-on: ubuntu-latest
    steps:
      - name: Show date
        run: echo "✅ cron 테스트 성공: $(date)"
